# Generated by Django 4.1.2 on 2022-10-26 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Region', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='town',
            name='fee',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
