# Generated by Django 4.1.2 on 2022-11-12 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Region', '0003_city_country_person_city_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='city',
        ),
        migrations.RemoveField(
            model_name='person',
            name='country',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
