# Generated by Django 4.1.2 on 2022-10-26 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0002_alter_order_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_address',
        ),
    ]
