# Generated by Django 4.1.2 on 2022-10-26 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Region', '0001_initial'),
        ('Orders', '0003_remove_order_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='county',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Region.county'),
        ),
        migrations.AddField(
            model_name='order',
            name='town',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Region.town'),
        ),
    ]
