# Generated by Django 4.1.2 on 2022-11-11 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0006_orderitems'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItems',
        ),
    ]
