# Generated by Django 4.1.2 on 2022-10-25 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
